menu:
  starters:
    - name: "PERCY POTATOES†"
      description: "crispy coal roasted, pickled shallot aioli, black garlic, fresh herbs"
    - name: "CRISPY CAULIFLOWER"
      description: "parsnip tahini, italian chili crisp, pickled carrot"
    - name: "SEASONAL VEGGIE"
      description: "best in season produce"

  sides:
    - name: "SEASONED FRIES†"
      description: ""
    - name: "LITTLE HOUSE SALAD"
      description: ""
    - name: "MISO SWEET POTATOES"
      description: ""

  entrees:
    - name: "FORBIDDEN RICE BOWL"
      description: "emperor’s black rice, seasonal veg, sweet chili vinaigrette"
    - name: "GRILLED BRANZINO"
      description: "smoked cauliflower & almond puree, swiss chard pesto, crispy brussels, pickled grapes"
    - name: "SEARED SALMON*"
      description: "toasted farro, mushroom consommé, charred broccolini"
    - name: "SKIRT STEAK*"
      description: "certified angus, lizzy’s backyard marinade, cheesy green chili rice"
      note: "Request no butter"
    - name: "STEAK FRITES*"
      description: "10oz new york strip, au poivre butter, seasoned fries†"
      note: "Request no butter"

