menu:
  starters:
    - name: "PERCY POTATOES†"
      description: "crispy coal roasted, pickled shallot aioli, black garlic, fresh herbs"
    - name: "CRISPY CAULIFLOWER"
      description: "parsnip tahini, italian chili crisp, pickled carrot"
    - name: "SEASONAL VEGGIE"
      description: "best in season produce"

  sides:
    - name: "SEASONED FRIES†"
      description: ""
    - name: "LITTLE HOUSE SALAD"
      description: ""
    - name: "MISO SWEET POTATOES"
      description: ""

  entrees:
    - name: "FORBIDDEN RICE BOWL"
      description: "emperor’s black rice, seasonal veg, sweet chili vinaigrette"
    - name: "SEARED SALMON*"
      description: "toasted farro, mushroom consommé, charred broccolini"
      note: "Request no butter"
    - name: "ORGANIC ROTISSERIE CHICKEN"
      description: "apricot glaze, mashed potato, braised greens"
      note: "Request no butter"
    - name: "STICKY RIBS"
      description: "st. louis cut, sweet potato medallions, miso mustard glaze, fresh herbs"
    - name: "SKIRT STEAK*"
      description: "certified angus, lizzy’s backyard marinade, cheesy green chili rice"
      note: "Request no butter"
    - name: "STEAK FRITES*"
      description: "10oz new york strip, au poivre butter, seasoned fries†"
      note: "Request no butter"
    - name: "SHORT RIB"
      description: "coffee-chili rubbed, mashed potato, baby carrots"
      note: "Request no butter"
    - name: "SOURDOUGH PAPPARDELLE"
      description: "short rib bolognese, burrata, calabrian chili oil"
      note: "Request no butter and no burrata"
    - name: "BRAISED PORK SHANK"
      description: "snake river farms kurobuta pork, horseradish mashed potato, gremolata"
      note: "Request no butter"

  desserts:
    - name: "CHOCOLATE CAKE"
      description: "chocolate mousse, chocolate cream cheese frosting, raspberry coulis"
